name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on .NET Core
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use .NET 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Building
        run: dotnet build          
          
      - name: Run Tests
        run: dotnet test
